import streamlit as st
import os
from backend import HybridSearchRAG

@st.cache_resource
def load_search_system():
    """Loads and indexes the corpus once. Cached so it only runs on first load."""
    data_paths = [
        r"C:\Users\Seif\Desktop\GenAI\DataSet\top_ai_questions.json",
        r"C:\Users\Seif\Desktop\GenAI\DataSet\top_datascience_questions.json"
    ]
    valid_paths = [p for p in data_paths if os.path.exists(p)]
    if not valid_paths:
        return None
    return HybridSearchRAG(valid_paths)

# ── Page config ──────────────────────────────────────────────────────
st.set_page_config(page_title="Hybrid Search QA Assistant", page_icon="🤖", layout="wide")
st.title("🤖 Technical QA Assistant")
st.markdown(
    "Ask any AI or Data Science question. Retrieval uses **BM25 + MiniLM (RRF)** "
    "and answers are generated by an open-source LLM via **OpenRouter**."
)
st.divider()

# Configuration Sidebar
with st.sidebar:
    st.header("⚙️ Configuration")
    st.markdown("Get a **free** API key at [openrouter.ai](https://openrouter.ai)")
    api_key = st.text_input("OpenRouter API Key", type="password", placeholder="sk-or-...")
    model_choice = "openai/gpt-oss-120b:free"
    st.caption(f"**Model:** `{model_choice}`")

# ── Load retrieval system ────────────────────────────────────────────
system = load_search_system()
if system is None:
    st.error("❌ Datasets not found. Check the file paths in `app.py`.")
    st.stop()

# ── Main Q&A interface ───────────────────────────────────────────────
query = st.text_input(
    "💬 Enter your question:",
    placeholder="e.g. What is the difference between strong AI and weak AI?"
)

if query:
    if not api_key:
        st.warning("⚠️ Please enter your OpenRouter API key in the sidebar.")
        st.stop()

    with st.spinner("🔍 Retrieving and generating answer..."):
        # Initialise (or re-initialise) with the chosen model
        system.load_rag_model(api_key=api_key, model_name=model_choice)

        # Hybrid search: BM25 + Semantic fused via RRF
        retrieved_docs = system.search_hybrid(query, top_k=5)

        # RAG generation
        answer = system.generate_answer(query, retrieved_docs)

    st.subheader("📝 Generated Answer")
    st.success(answer)

    # Show which model OpenRouter actually used
    st.caption(f"ℹ️ Model used: `{model_choice}`")

    st.subheader("📚 Sources Used")
    for i, doc in enumerate(retrieved_docs[:3]):
        with st.expander(f"Source {i+1}: {doc['doc']['title']}"):
            st.markdown(f"🔗 [View original post]({doc['doc']['link']})")
            st.markdown(f"*{doc['doc']['text'][:400]}...*")
